### ISSUE TITLE
minor wordsmithing requests for help page.

### ISSUE THREAD

**Issue by mariev** [ABS-dev/PF#13]
Comment here with requests for minor changes/edits to text only on help pages. This is for requests that do not affect usage of any function. [PDF of all help pages](https://github.com/ABS-dev/PF/blob/master/inst/doc/PF-manual.pdf)

**Comment by mariev** [comment]
update usage for `.rr.score.asymp ` to match code. Currently:

```
.rr.score.asymp(y)
```

should be:

```
.rr.score.asymp(y, alpha = 0.05, iter.max = 18, converge = 1e-04, mn = FALSE)
```

**Comment by marireisdorf** [comment]
In RRtosst, the y argument is defined as, "Data vector c(y1, n1, y2, n2) where y are the positives, n are the total, and group 1 is compared to group 2."
In RRmh and RRstr, the compare argument is defined as, "Text vector stating the factor levels: compare[1] is the control or reference group to which compare[2] is compared."

Could RRtosst have a similar description of group 1 and group 2 so that it is more clear? Suggestion: "..., and group 1 (vaccinate) is compared to group 2 (control)."

**Comment by mariev** [comment]
`RRmh` help page incorrectly states that the `rr1` object output (under **Value**) has slot "compare". This needs to be removed. The `rr1` class help page is correct.

**Comment by mariev** [comment]
RRmpWald does not return `$multvec` object when input is vector, by design. Need to make a note of this, not obvious in examples.

**Comment by mariev** [comment]
multiple references to PF package vignette in help pages. Identify whether this is referring to StatWI (which cannot be accessed via `vignette(package = "PF")` or a document that is actually part of the package

**Comment by mariev** [comment]
conventions for y_i, n_i, compare_i to be unified using 1 = vaccinate and 2 = control

**Comment by mariev** [comment]
S4 class rr1 needs updated documentation. syntax now triggers warning during R CMD check
